[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "python-webview"
version = "0.1.0"
description = "Python bindings for the webview library"
readme = "README.md"
authors = [{ name = "Python Webview Team", email = "info@python-webview.org" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Software Development :: User Interfaces",
]
keywords = ["webview", "gui", "desktop", "application", "html", "web"]
dependencies = []
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/python-webview/python-webview"
Documentation = "https://python-webview.readthedocs.io"
Repository = "https://github.com/python-webview/python-webview.git"
"Bug Tracker" = "https://github.com/python-webview/python-webview/issues"

[tool.setuptools.packages.find]
where = ["src"]
include = ["python_webview*"]
namespaces = false

[tool.setuptools.package-data]
python_webview = ["py.typed"]

[tool.black]
line-length = 100
target-version = ['py37']

[tool.isort]
profile = "black"
line_length = 100
